-- CRM payment requests collected through Authorize.net Accept Hosted.
-- Additive except for the listed CREATE OR REPLACE / constraint changes. The
-- application keeps the feature inert unless PAYMENTS_ENABLED=true and all
-- Authorize.net credentials are configured. Card data never reaches this
-- database: only the processor's transaction id, status, card brand and last
-- four digits are stored. Authorize.net remains the financial system of record.

create table public.payment_requests (
  id uuid primary key default gen_random_uuid(),
  -- No contacts FK: recoverable trash temporarily removes the contact row while
  -- keeping its payment history; the guard trigger below requires an active
  -- contact for new or re-pointed rows.
  contact_id uuid not null,
  -- Human reference and Authorize.net invoiceNumber (max 20 characters).
  reference text not null unique check (reference ~ '^CRP-[2-9A-HJKMNP-Z]{8}$'),
  link_token text not null unique check (link_token ~ '^[A-Za-z0-9_-]{43}$'),
  amount_cents integer not null check (amount_cents between 100 and 2500000),
  currency text not null default 'USD' check (currency = 'USD'),
  description text not null check (length(description) between 3 and 255),
  status text not null default 'open' check (status in ('open', 'paid', 'cancelled', 'failed')),
  created_by uuid references public.crm_users(user_id) on delete set null,
  created_by_name text not null,
  checkout_count integer not null default 0,
  last_checkout_at timestamptz,
  held_transaction_id text,
  failure_reason text,
  failed_at timestamptz,
  paid_at timestamptz,
  transaction_id text unique,
  transaction_status text,
  paid_amount_cents integer,
  card_brand text,
  card_last4 text check (card_last4 is null or card_last4 ~ '^[0-9]{4}$'),
  payer_email text,
  cancelled_at timestamptz,
  cancelled_by uuid references public.crm_users(user_id) on delete set null,
  email_send_count integer not null default 0,
  last_email_queued_at timestamptz,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  check (status <> 'paid' or (paid_at is not null and transaction_id is not null)),
  check (status = 'paid' or transaction_id is null),
  check (status <> 'cancelled' or cancelled_at is not null),
  check (status <> 'failed' or failure_reason is not null)
);
-- Target of the composite email-enrollment FK below.
create unique index payment_requests_id_contact_idx on public.payment_requests(id, contact_id);
create index payment_requests_contact_idx on public.payment_requests(contact_id, created_at desc);

create table public.payment_request_events (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.payment_requests(id) on delete cascade,
  actor_id uuid references public.crm_users(user_id) on delete set null,
  -- Staff display name | 'client' | 'system' | 'authorize.net'.
  actor_name text not null,
  action text not null check (action in (
    'created', 'link_emailed', 'checkout_started', 'checkout_failed', 'paid', 'failed', 'held',
    'voided', 'refunded', 'cancelled', 'duplicate_payment', 'paid_after_cancel', 'amount_mismatch', 'ignored'
  )),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default clock_timestamp()
);
create index payment_request_events_request_idx on public.payment_request_events(request_id, created_at desc, id desc);

-- Operational webhook log for idempotency. Excluded from CRM backups.
create table public.payment_webhook_events (
  notification_id text primary key check (length(notification_id) between 1 and 200),
  event_type text not null,
  transaction_id text,
  request_id uuid references public.payment_requests(id) on delete set null,
  outcome text not null default 'received' check (outcome in ('received', 'processed', 'ignored', 'retry')),
  payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default clock_timestamp(),
  processed_at timestamptz
);

alter table public.payment_requests enable row level security;
alter table public.payment_request_events enable row level security;
alter table public.payment_webhook_events enable row level security;
revoke all on public.payment_requests, public.payment_request_events, public.payment_webhook_events
  from public, anon, authenticated;
grant all on public.payment_requests, public.payment_request_events, public.payment_webhook_events to service_role;
grant usage, select on sequence public.payment_request_events_id_seq to service_role;

create function public.guard_payment_request_contact_v1()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if not exists (select 1 from public.contacts c where c.id = new.contact_id) then
    raise exception 'payment_request_contact_unavailable';
  end if;
  return new;
end;
$$;
create trigger payment_request_contact_guard
  before insert or update of contact_id on public.payment_requests
  for each row execute function public.guard_payment_request_contact_v1();
create trigger payment_requests_set_updated_at
  before update on public.payment_requests
  for each row execute function public.set_updated_at();

-- Email-queue linkage: a payment link email rides the durable queue under its
-- own enrollment context `payment:<request id>`.
alter table public.sequence_enrollments
  add column payment_request_id uuid,
  add constraint enrollments_payment_request_contact_fk foreign key (payment_request_id, contact_id)
    references public.payment_requests(id, contact_id) on delete cascade,
  drop constraint enrollments_context_consistent,
  add constraint enrollments_context_consistent check (
    (context_key = 'legacy' and live_registration_id is null and payment_request_id is null
      and sequence_key not in ('live_webinar', 'payment_request'))
    or (live_registration_id is not null and payment_request_id is null
      and context_key = 'live:' || live_registration_id::text and sequence_key = 'live_webinar')
    or (payment_request_id is not null and live_registration_id is null
      and context_key = 'payment:' || payment_request_id::text and sequence_key = 'payment_request')
  );
create index sequence_enrollments_payment_request_idx on public.sequence_enrollments(payment_request_id)
  where payment_request_id is not null;

-- Unchanged from 20260912101000 apart from the added payment arm. Payment link
-- emails are transactional: universal suppression blocks them, marketing
-- consent and unsubscribe do not.
create or replace function public.email_message_is_eligible(p_contact_id uuid,p_enrollment_id uuid,p_template_key text)
returns boolean language sql stable security definer set search_path = '' as $$
  select coalesce((select c.email_suppressed_at is null and e.status = 'active' and (
    (e.context_key = 'legacy'
      and (e.sequence_key = 'onboarding' or p_template_key = 'pre_webinar:1' or (c.marketing_consent and c.unsubscribed_at is null))
      and not (e.sequence_key <> 'onboarding' and exists (select 1 from public.events v where v.contact_id=c.id and v.event_key='call_booked'))
      and not (e.sequence_key='pre_webinar' and p_template_key <> 'pre_webinar:1' and exists (
        select 1 from public.events v where v.contact_id=c.id and coalesce(v.properties->>'funnel','') <> 'live'
        and v.event_key in ('webinar_room_opened','webinar_watch_25','webinar_watch_50','webinar_watch_75','webinar_watch_90','webinar_completed')
      )))
    or (e.live_registration_id is not null and exists (
      select 1 from public.live_webinar_registrations r join public.live_webinar_sessions s on s.id=r.session_id
      where r.id=e.live_registration_id and r.contact_id=c.id and r.cancelled_at is null
        and not r.notifications_paused and s.automation_enabled
        and ((p_template_key in ('live_confirmation:1','live_reminder_day:1','live_reminder_soon:1','live_rescheduled:1') and s.status='scheduled')
          or (p_template_key='live_cancelled:1' and s.status='cancelled')
          or (p_template_key in ('live_attended:1','live_no_show:1','live_replay:1') and s.status='scheduled'
            and c.marketing_consent and c.unsubscribed_at is null and c.stage not in ('won','lost','booked','call_booked')
            and not exists (select 1 from public.events v where v.contact_id=c.id and v.event_key='call_booked')))
    ))
    or (e.payment_request_id is not null and exists (
      select 1 from public.payment_requests p
      where p.id=e.payment_request_id and p.contact_id=c.id and p.status in ('open','failed')
    ))
  ) from public.contacts c join public.sequence_enrollments e on e.contact_id=c.id and e.id=p_enrollment_id
    where c.id=p_contact_id),false);
$$;

create or replace function public.email_message_is_eligible_v2(p_message_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select coalesce((select public.email_message_is_eligible(m.contact_id,m.enrollment_id,m.template_key)
    and (e.context_key='legacy'
    or (e.payment_request_id is not null and m.payload->>'paymentRequestId'=e.payment_request_id::text)
    or (
      m.payload->>'registrationId'=r.id::text and m.payload->>'sessionId'=s.id::text
      and m.payload->>'accessVersion'=r.access_version::text
      and m.payload->>'sessionVersion'=s.schedule_version::text
      and (nullif(m.payload->>'sendDeadline','') is null or (m.payload->>'sendDeadline')::timestamptz>now())
      and case m.template_key
        when 'live_confirmation:1' then now()<s.ends_at
        when 'live_reminder_day:1' then now()<s.starts_at-interval '15 minutes'
        when 'live_reminder_soon:1' then now()<s.starts_at
        when 'live_rescheduled:1' then now()<s.ends_at
        when 'live_cancelled:1' then s.status='cancelled'
        when 'live_attended:1' then now()>=s.ends_at+make_interval(mins=>s.attendance_grace_minutes) and r.attended_at is not null
        when 'live_no_show:1' then now()>=s.ends_at+make_interval(mins=>s.attendance_grace_minutes) and r.attended_at is null
        when 'live_replay:1' then s.replay_published and s.replay_url is not null and now()>=s.ends_at
          and (s.replay_available_until is null or s.replay_available_until>now())
        else false end
    ))
    from public.scheduled_messages m join public.sequence_enrollments e on e.id=m.enrollment_id
    left join public.live_webinar_registrations r on r.id=e.live_registration_id
    left join public.live_webinar_sessions s on s.id=r.session_id where m.id=p_message_id),false);
$$;

-- Payment link emails are claimed by the cron worker even while live webinar
-- delivery is disabled (the legacy predicate is extended to payment contexts).
create or replace function public.claim_due_scheduled_emails_v2(p_limit integer default 10,p_include_live boolean default false)
returns table(message_id uuid,email text,template_key text,payload jsonb)
language plpgsql security definer set search_path = '' as $$
begin
  if p_limit<1 or p_limit>100 then raise exception 'invalid_limit'; end if;
  update public.scheduled_messages set status='scheduled',updated_at=now()
    where status='sending' and updated_at<now()-interval '15 minutes'
      and (p_include_live or enrollment_id in (select id from public.sequence_enrollments where context_key='legacy' or payment_request_id is not null));
  update public.scheduled_messages m set status='cancelled',last_error='Cancelled at send time: no longer eligible',updated_at=now()
    where m.status='scheduled' and m.scheduled_for<=now() and not public.email_message_is_eligible_v2(m.id)
      and (p_include_live or m.enrollment_id in (select id from public.sequence_enrollments where context_key='legacy' or payment_request_id is not null))
      -- A disabled session is paused, not permanently consumed by an old worker.
      and not exists (select 1 from public.sequence_enrollments e join public.live_webinar_registrations r on r.id=e.live_registration_id
        join public.live_webinar_sessions s on s.id=r.session_id where e.id=m.enrollment_id and not s.automation_enabled);
  return query with due as (
    select m.id from public.scheduled_messages m where m.status='scheduled' and m.scheduled_for<=now()
      and (p_include_live or m.enrollment_id in (select id from public.sequence_enrollments where context_key='legacy' or payment_request_id is not null))
      and public.email_message_is_eligible_v2(m.id) order by m.scheduled_for,m.id for update of m skip locked limit p_limit
  ), claimed as (
    update public.scheduled_messages m set status='sending',attempts=m.attempts+1,last_error=null,updated_at=now()
      from due where m.id=due.id returning m.id,m.contact_id,m.template_key,m.payload
  ) select m.id,c.email::text,m.template_key,m.payload from claimed m join public.contacts c on c.id=m.contact_id;
end; $$;

-- Signature unchanged; adds the 'payment' bucket for the public pay routes.
create or replace function public.consume_rate_limit(
  p_bucket text,
  p_key_hash text,
  p_window_seconds integer,
  p_limit integer
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_window timestamptz;
  current_count integer;
begin
  if p_bucket not in ('registration', 'booking', 'tracking', 'live-question', 'live-activity', 'payment') then raise exception 'invalid_bucket'; end if;
  if p_key_hash !~ '^[0-9a-f]{64}$' then raise exception 'invalid_key_hash'; end if;
  if p_window_seconds < 10 or p_window_seconds > 3600 then raise exception 'invalid_window'; end if;
  if p_limit < 1 or p_limit > 1000 then raise exception 'invalid_limit'; end if;

  current_window := to_timestamp(floor(extract(epoch from clock_timestamp()) / p_window_seconds) * p_window_seconds);

  delete from public.rate_limit_counters
  where bucket = p_bucket and key_hash = p_key_hash
    and window_start < current_window - interval '1 hour';

  insert into public.rate_limit_counters (bucket, key_hash, window_start, request_count)
  values (p_bucket, p_key_hash, current_window, 1)
  on conflict (bucket, key_hash, window_start) do update
  set request_count = public.rate_limit_counters.request_count + 1
  returning request_count into current_count;

  return current_count <= p_limit;
end;
$$;

-- One CRM list item. Used by create and list so both return the same shape.
create function public.payment_request_item_v1(p_request_id uuid)
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'id', p.id, 'reference', p.reference, 'linkToken', p.link_token,
    'amountCents', p.amount_cents, 'currency', p.currency, 'description', p.description,
    'status', p.status, 'createdAt', p.created_at, 'createdByName', p.created_by_name,
    'paidAt', p.paid_at, 'transactionId', p.transaction_id, 'transactionStatus', p.transaction_status,
    'paidAmountCents', p.paid_amount_cents, 'cardBrand', p.card_brand, 'cardLast4', p.card_last4,
    'payerEmail', p.payer_email, 'failureReason', p.failure_reason, 'failedAt', p.failed_at,
    'heldTransactionId', p.held_transaction_id, 'cancelledAt', p.cancelled_at,
    'checkoutCount', p.checkout_count, 'lastCheckoutAt', p.last_checkout_at,
    'emailSendCount', p.email_send_count, 'lastEmailQueuedAt', p.last_email_queued_at,
    'lastEmail', (
      select jsonb_build_object('status', m.status, 'scheduledFor', m.scheduled_for, 'sentAt', m.sent_at, 'lastError', m.last_error)
      from public.scheduled_messages m join public.sequence_enrollments e on e.id = m.enrollment_id
      where e.payment_request_id = p.id
      order by m.created_at desc, m.id desc limit 1
    ),
    'events', coalesce((
      select jsonb_agg(jsonb_build_object('action', x.action, 'actorName', x.actor_name, 'createdAt', x.created_at, 'details', x.details)
        order by x.created_at desc, x.id desc)
      from (select ev.* from public.payment_request_events ev where ev.request_id = p.id
        order by ev.created_at desc, ev.id desc limit 20) x
    ), '[]'::jsonb)
  ) from public.payment_requests p where p.id = p_request_id;
$$;

create function public.create_payment_request_v1(
  p_contact_id uuid, p_amount_cents integer, p_description text, p_actor_id uuid, p_reference text, p_link_token text
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare actor_name text; contact_row public.contacts%rowtype; clean_description text := trim(coalesce(p_description, '')); new_id uuid;
begin
  select display_name into actor_name from public.crm_users where user_id = p_actor_id and role in ('admin', 'staff');
  if not found then raise exception 'payment_request_actor_invalid'; end if;
  select * into contact_row from public.contacts where id = p_contact_id;
  if not found then raise exception 'payment_request_contact_unavailable'; end if;
  if p_amount_cents is null or p_amount_cents < 100 or p_amount_cents > 2500000 then
    raise exception 'payment_request_amount_invalid';
  end if;
  if length(clean_description) < 3 or length(clean_description) > 255 or clean_description ~ '[[:cntrl:]]' then
    raise exception 'payment_request_description_invalid';
  end if;
  insert into public.payment_requests(contact_id, reference, link_token, amount_cents, description, created_by, created_by_name)
  values (p_contact_id, p_reference, p_link_token, p_amount_cents, clean_description, p_actor_id, coalesce(actor_name, 'CRM user'))
  returning id into new_id;
  insert into public.payment_request_events(request_id, actor_id, actor_name, action, details)
  values (new_id, p_actor_id, coalesce(actor_name, 'CRM user'), 'created',
    jsonb_build_object('amountCents', p_amount_cents, 'reference', p_reference));
  insert into public.events(event_key, contact_id, email, properties)
  values ('payment_request_created', contact_row.id, contact_row.email, jsonb_build_object(
    'amountCents', p_amount_cents, 'reference', p_reference, 'description', clean_description));
  return public.payment_request_item_v1(new_id);
end;
$$;

create function public.list_payment_requests_v1(p_contact_id uuid)
returns jsonb language sql stable security definer set search_path = '' as $$
  select case when not exists (select 1 from public.contacts c where c.id = p_contact_id) then '[]'::jsonb
  else coalesce((
    select jsonb_agg(public.payment_request_item_v1(q.id) order by q.created_at desc, q.id desc)
    from (select p.id, p.created_at from public.payment_requests p where p.contact_id = p_contact_id
      order by p.created_at desc, p.id desc limit 200) q
  ), '[]'::jsonb) end;
$$;

-- Public page lookup. Never returns the contact email or the link token.
create function public.find_payment_request_by_token_v1(p_token text)
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'id', p.id, 'reference', p.reference, 'amountCents', p.amount_cents, 'currency', p.currency,
    'description', p.description, 'status', p.status, 'paidAt', p.paid_at, 'transactionId', p.transaction_id,
    'held', p.held_transaction_id is not null, 'cancelledAt', p.cancelled_at,
    'contactFirstName', nullif(split_part(trim(c.name), ' ', 1), ''),
    'payable', p.status in ('open', 'failed') and p.held_transaction_id is null
  )
  from public.payment_requests p join public.contacts c on c.id = p.contact_id
  where p_token ~ '^[A-Za-z0-9_-]{43}$' and p.link_token = p_token;
$$;

create function public.begin_payment_checkout_v1(p_token text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare r public.payment_requests%rowtype; c_email text; c_name text;
begin
  if p_token is null or p_token !~ '^[A-Za-z0-9_-]{43}$' then raise exception 'payment_request_missing'; end if;
  select * into r from public.payment_requests where link_token = p_token for update;
  if not found then raise exception 'payment_request_missing'; end if;
  select c.email::text, c.name into c_email, c_name from public.contacts c where c.id = r.contact_id;
  if not found then raise exception 'payment_request_missing'; end if;
  if r.status not in ('open', 'failed') or r.held_transaction_id is not null then
    raise exception 'payment_request_not_payable';
  end if;
  update public.payment_requests set checkout_count = checkout_count + 1, last_checkout_at = clock_timestamp()
    where id = r.id;
  insert into public.payment_request_events(request_id, actor_name, action, details)
  values (r.id, 'client', 'checkout_started', jsonb_build_object('checkoutCount', r.checkout_count + 1));
  return jsonb_build_object('id', r.id, 'reference', r.reference, 'amountCents', r.amount_cents,
    'description', r.description, 'contactEmail', c_email, 'contactName', c_name);
end;
$$;

create function public.record_payment_request_event_v1(p_request_id uuid, p_action text, p_actor_name text, p_details jsonb)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if not exists (select 1 from public.payment_requests where id = p_request_id) then return false; end if;
  insert into public.payment_request_events(request_id, actor_name, action, details)
  values (p_request_id, left(coalesce(nullif(trim(p_actor_name), ''), 'system'), 100), p_action,
    case when jsonb_typeof(p_details) = 'object' then p_details else '{}'::jsonb end);
  return true;
end;
$$;

-- The only writer of paid state. Idempotent per (reference, transaction id).
create function public.apply_payment_transaction_v1(
  p_reference text, p_transaction_id text, p_outcome text, p_details jsonb, p_source text
)
returns text language plpgsql security definer set search_path = '' as $$
declare
  r public.payment_requests%rowtype;
  d jsonb := case when jsonb_typeof(p_details) = 'object' then p_details else '{}'::jsonb end;
  v_amount integer; v_submitted timestamptz; v_status text; v_brand text; v_last4 text; v_email text; v_reason text;
  v_source text := left(coalesce(nullif(trim(p_source), ''), 'unknown'), 40);
  v_event jsonb; c_email public.citext; c_exists boolean;
begin
  if p_outcome is null or p_outcome not in ('approved', 'declined', 'error', 'held', 'voided', 'refunded') then
    raise exception 'payment_outcome_invalid';
  end if;
  -- Sandbox "Test Mode" returns transId 0 for every transaction; never record it.
  if p_transaction_id is null or p_transaction_id !~ '^[A-Za-z0-9_-]{1,64}$' or p_transaction_id = '0' then
    raise exception 'payment_transaction_invalid';
  end if;
  select * into r from public.payment_requests where reference = p_reference for update;
  if not found then return 'unknown_reference'; end if;

  if jsonb_typeof(d->'amountCents') = 'number' and (d->>'amountCents')::numeric between 0 and 2147483647 then
    v_amount := round((d->>'amountCents')::numeric)::integer;
  end if;
  begin
    v_submitted := nullif(d->>'submittedAt', '')::timestamptz;
  exception when others then v_submitted := null;
  end;
  if v_submitted > clock_timestamp() + interval '1 day' then v_submitted := null; end if;
  v_status := left(nullif(trim(d->>'transactionStatus'), ''), 60);
  v_brand := left(nullif(trim(d->>'cardBrand'), ''), 40);
  v_last4 := case when d->>'cardLast4' ~ '^[0-9]{4}$' then d->>'cardLast4' end;
  v_email := left(nullif(trim(d->>'payerEmail'), ''), 254);
  v_reason := left(nullif(trim(d->>'reason'), ''), 255);
  v_event := jsonb_strip_nulls(jsonb_build_object('transactionId', p_transaction_id, 'source', v_source,
    'amountCents', v_amount, 'transactionStatus', v_status, 'responseCode', d->'responseCode'));
  select c.email, true into c_email, c_exists from public.contacts c where c.id = r.contact_id;
  c_exists := coalesce(c_exists, false);

  if p_outcome = 'approved' then
    if r.status = 'paid' then
      if r.transaction_id = p_transaction_id then return 'already_paid'; end if;
      if not exists (select 1 from public.payment_request_events where request_id = r.id
          and action = 'duplicate_payment' and details->>'transactionId' = p_transaction_id) then
        insert into public.payment_request_events(request_id, actor_name, action, details)
        values (r.id, 'authorize.net', 'duplicate_payment', v_event);
      end if;
      return 'duplicate_payment';
    end if;
    update public.payment_requests set status = 'paid', paid_at = coalesce(v_submitted, clock_timestamp()),
      transaction_id = p_transaction_id, transaction_status = v_status, paid_amount_cents = v_amount,
      card_brand = v_brand, card_last4 = v_last4, payer_email = v_email,
      held_transaction_id = null, failure_reason = null
      where id = r.id;
    insert into public.payment_request_events(request_id, actor_name, action, details)
    values (r.id, 'authorize.net', 'paid', v_event);
    if v_amount is not null and v_amount <> r.amount_cents then
      insert into public.payment_request_events(request_id, actor_name, action, details)
      values (r.id, 'authorize.net', 'amount_mismatch', v_event || jsonb_build_object('expectedAmountCents', r.amount_cents));
    end if;
    if r.status = 'cancelled' then
      insert into public.payment_request_events(request_id, actor_name, action, details)
      values (r.id, 'authorize.net', 'paid_after_cancel', v_event);
    end if;
    update public.scheduled_messages set status = 'cancelled', last_error = 'Payment received', updated_at = now()
      where status = 'scheduled'
        and enrollment_id in (select e.id from public.sequence_enrollments e where e.payment_request_id = r.id);
    if c_exists then
      insert into public.events(event_key, contact_id, email, properties)
      values ('payment_received', r.contact_id, c_email, jsonb_strip_nulls(jsonb_build_object(
        'amountCents', r.amount_cents, 'paidAmountCents', v_amount, 'reference', r.reference,
        'description', r.description, 'transactionId', p_transaction_id)));
    end if;
    return 'paid';
  end if;

  if p_outcome in ('declined', 'error') then
    if r.status in ('paid', 'cancelled') then
      if not exists (select 1 from public.payment_request_events where request_id = r.id
          and action = 'ignored' and details->>'transactionId' = p_transaction_id) then
        insert into public.payment_request_events(request_id, actor_name, action, details)
        values (r.id, 'authorize.net', 'ignored', v_event || jsonb_build_object('outcome', p_outcome));
      end if;
      return 'ignored';
    end if;
    if exists (select 1 from public.payment_request_events where request_id = r.id
        and action = 'failed' and details->>'transactionId' = p_transaction_id) then
      return 'failed';
    end if;
    update public.payment_requests set status = 'failed',
      failure_reason = coalesce(v_reason, case when p_outcome = 'declined' then 'Card declined' else 'Processing error' end),
      failed_at = clock_timestamp(),
      held_transaction_id = case when held_transaction_id = p_transaction_id then null else held_transaction_id end
      where id = r.id;
    insert into public.payment_request_events(request_id, actor_name, action, details)
    values (r.id, 'authorize.net', 'failed', v_event || jsonb_build_object('outcome', p_outcome));
    if c_exists then
      insert into public.events(event_key, contact_id, email, properties)
      values ('payment_failed', r.contact_id, c_email, jsonb_build_object(
        'amountCents', r.amount_cents, 'reference', r.reference, 'description', r.description));
    end if;
    return 'failed';
  end if;

  if p_outcome = 'held' then
    if r.status in ('paid', 'cancelled') then
      if not exists (select 1 from public.payment_request_events where request_id = r.id
          and action = 'ignored' and details->>'transactionId' = p_transaction_id) then
        insert into public.payment_request_events(request_id, actor_name, action, details)
        values (r.id, 'authorize.net', 'ignored', v_event || jsonb_build_object('outcome', p_outcome));
      end if;
      return 'ignored';
    end if;
    if r.held_transaction_id is distinct from p_transaction_id then
      update public.payment_requests set held_transaction_id = p_transaction_id where id = r.id;
      insert into public.payment_request_events(request_id, actor_name, action, details)
      values (r.id, 'authorize.net', 'held', v_event);
    end if;
    return 'held';
  end if;

  -- voided / refunded: recorded only. Refunds and voids happen in Authorize.net.
  if not exists (select 1 from public.payment_request_events where request_id = r.id
      and action = p_outcome and details->>'transactionId' = p_transaction_id) then
    insert into public.payment_request_events(request_id, actor_name, action, details)
    values (r.id, 'authorize.net', p_outcome, v_event);
  end if;
  return 'recorded';
end;
$$;

-- p_contact_id (optional) scopes the mutation to the contact the CRM user opened.
create function public.cancel_payment_request_v1(p_request_id uuid, p_actor_id uuid, p_contact_id uuid default null)
returns boolean language plpgsql security definer set search_path = '' as $$
declare actor_name text; r public.payment_requests%rowtype; c_email public.citext;
begin
  select display_name into actor_name from public.crm_users where user_id = p_actor_id and role in ('admin', 'staff');
  if not found then raise exception 'payment_request_actor_invalid'; end if;
  select * into r from public.payment_requests where id = p_request_id for update;
  if not found or (p_contact_id is not null and r.contact_id <> p_contact_id) then
    raise exception 'payment_request_missing';
  end if;
  if r.status = 'cancelled' then return true; end if;
  if r.status = 'paid' then raise exception 'payment_request_not_cancellable'; end if;
  update public.payment_requests set status = 'cancelled', cancelled_at = clock_timestamp(), cancelled_by = p_actor_id
    where id = r.id;
  update public.scheduled_messages set status = 'cancelled', last_error = 'Payment request cancelled', updated_at = now()
    where status = 'scheduled'
      and enrollment_id in (select e.id from public.sequence_enrollments e where e.payment_request_id = r.id);
  insert into public.payment_request_events(request_id, actor_id, actor_name, action, details)
  values (r.id, p_actor_id, coalesce(actor_name, 'CRM user'), 'cancelled', jsonb_build_object('previousStatus', r.status));
  select c.email into c_email from public.contacts c where c.id = r.contact_id;
  if found then
    insert into public.events(event_key, contact_id, email, properties)
    values ('payment_request_cancelled', r.contact_id, c_email, jsonb_build_object(
      'amountCents', r.amount_cents, 'reference', r.reference, 'description', r.description));
  end if;
  return true;
end;
$$;

create function public.begin_payment_webhook_v1(p_notification_id text, p_event_type text, p_transaction_id text, p_payload jsonb)
returns text language plpgsql security definer set search_path = '' as $$
declare existing_outcome text;
begin
  insert into public.payment_webhook_events(notification_id, event_type, transaction_id, payload)
  values (p_notification_id, left(coalesce(p_event_type, ''), 200), left(p_transaction_id, 64),
    case when jsonb_typeof(p_payload) = 'object' then p_payload else '{}'::jsonb end)
  on conflict (notification_id) do nothing;
  if found then return 'new'; end if;
  select outcome into existing_outcome from public.payment_webhook_events where notification_id = p_notification_id;
  if existing_outcome in ('processed', 'ignored') then return 'duplicate'; end if;
  return 'retry';
end;
$$;

create function public.finish_payment_webhook_v1(p_notification_id text, p_outcome text, p_request_id uuid)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if p_outcome not in ('processed', 'ignored', 'retry') then raise exception 'payment_webhook_outcome_invalid'; end if;
  -- Without an explicit request id, link the log row through the transaction id
  -- recorded on the request or in its payment events.
  update public.payment_webhook_events w set outcome = p_outcome,
    request_id = coalesce(p_request_id, w.request_id, (
      select p.id from public.payment_requests p
      where w.transaction_id is not null and (p.transaction_id = w.transaction_id or p.held_transaction_id = w.transaction_id)
      limit 1
    ), (
      select ev.request_id from public.payment_request_events ev
      where w.transaction_id is not null and ev.details->>'transactionId' = w.transaction_id
      order by ev.id desc limit 1
    )),
    processed_at = case when p_outcome = 'retry' then null else clock_timestamp() end
    where notification_id = p_notification_id;
  return found;
end;
$$;

create function public.queue_payment_request_email_v1(p_request_id uuid, p_actor_id uuid, p_contact_id uuid default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare actor_name text; r public.payment_requests%rowtype; c public.contacts%rowtype; e_id uuid; m_id uuid; key text;
begin
  select display_name into actor_name from public.crm_users where user_id = p_actor_id and role in ('admin', 'staff');
  if not found then raise exception 'payment_request_actor_invalid'; end if;
  select * into r from public.payment_requests where id = p_request_id for update;
  if not found or (p_contact_id is not null and r.contact_id <> p_contact_id) then
    raise exception 'payment_request_missing';
  end if;
  if r.status not in ('open', 'failed') then raise exception 'payment_request_not_payable'; end if;
  select * into c from public.contacts where id = r.contact_id;
  if not found then raise exception 'payment_request_contact_unavailable'; end if;
  if c.email_suppressed_at is not null then raise exception 'payment_email_suppressed'; end if;
  if r.last_email_queued_at is not null and r.last_email_queued_at > clock_timestamp() - interval '60 seconds' then
    raise exception 'payment_email_too_soon';
  end if;

  insert into public.sequence_enrollments(contact_id, sequence_key, context_key, payment_request_id)
  values (r.contact_id, 'payment_request', 'payment:' || r.id::text, r.id)
  on conflict (contact_id, sequence_key, context_key) do update set status = 'active', stopped_at = null, stop_reason = null
  returning id into e_id;

  key := 'payment_request:' || r.id::text || ':' || gen_random_uuid()::text;
  insert into public.scheduled_messages(enrollment_id, contact_id, template_key, delivery_key, scheduled_for, payload)
  values (e_id, r.contact_id, key, key, now(), jsonb_build_object(
    'paymentRequestId', r.id, 'paymentLinkToken', r.link_token, 'amountCents', r.amount_cents,
    'paymentDescription', r.description, 'paymentReference', r.reference,
    'firstName', nullif(split_part(trim(c.name), ' ', 1), '')))
  returning id into m_id;

  update public.payment_requests set email_send_count = email_send_count + 1, last_email_queued_at = clock_timestamp()
    where id = r.id;
  insert into public.payment_request_events(request_id, actor_id, actor_name, action, details)
  values (r.id, p_actor_id, coalesce(actor_name, 'CRM user'), 'link_emailed', jsonb_build_object('messageId', m_id));
  return jsonb_build_object('messageId', m_id, 'templateKey', key, 'email', c.email::text);
end;
$$;

create function public.claim_payment_request_email_v1(p_message_id uuid)
returns table(id uuid,template_key text,payload jsonb)
language plpgsql security definer set search_path = '' as $$
begin
  return query with due as (
    select m.id from public.scheduled_messages m join public.sequence_enrollments e on e.id=m.enrollment_id
    where m.id=p_message_id and e.payment_request_id is not null
      and m.status='scheduled' and m.scheduled_for<=now()+interval '1 minute' and public.email_message_is_eligible_v2(m.id)
    for update of m skip locked
  ) update public.scheduled_messages m set status='sending',attempts=m.attempts+1,last_error=null,updated_at=now()
      from due where m.id=due.id returning m.id,m.template_key,m.payload;
end; $$;

-- Backup v4: adds payment requests and their audit trail. Staff UUIDs are
-- removed; the link token is kept so restored links keep working.
create function public.export_crm_backup_v4()
returns jsonb language sql stable security definer set search_path = '' as $$
  with base as materialized (select public.export_crm_backup_v3() as payload)
  select jsonb_set(jsonb_set(base.payload, '{version}', '4'::jsonb), '{tables}',
    (base.payload->'tables') || jsonb_build_object(
      'payment_requests', coalesce((select jsonb_agg(to_jsonb(p) || jsonb_build_object('created_by', null, 'cancelled_by', null))
        from public.payment_requests p where exists(select 1 from public.contacts c where c.id=p.contact_id)), '[]'::jsonb),
      'payment_request_events', coalesce((select jsonb_agg(to_jsonb(ev) || jsonb_build_object('actor_id', null))
        from public.payment_request_events ev join public.payment_requests p on p.id=ev.request_id
        where exists(select 1 from public.contacts c where c.id=p.contact_id)), '[]'::jsonb)
    )) from base;
$$;

create or replace function public.export_crm_backup_v1()
returns jsonb language sql stable security definer set search_path = '' as $$
  select public.export_crm_backup_v4();
$$;

create or replace function public.restore_crm_backup_v1(p_backup jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare table_data jsonb := p_backup->'tables'; restored_contacts integer;
begin
  if coalesce(p_backup->>'format', '') <> 'vance-crm-backup' or coalesce((p_backup->>'version')::integer, 0) not in (1,2,3,4) then raise exception 'unsupported_backup_format'; end if;
  if jsonb_typeof(table_data) <> 'object' then raise exception 'missing_backup_tables'; end if;
  delete from public.scheduled_messages where id is not null;
  delete from public.sequence_enrollments where id is not null;
  delete from public.payment_request_events where id is not null;
  delete from public.payment_requests where id is not null;
  delete from public.bookings where id is not null;
  delete from public.notes where id is not null;
  delete from public.tasks where id is not null;
  delete from public.contact_tags where contact_id is not null;
  delete from public.tags where id is not null;
  delete from public.events where id is not null;
  delete from public.live_webinar_registrations where id is not null;
  delete from public.credit_report_followup_audit where id is not null;
  delete from public.credit_report_followup_contact_attempts where id is not null;
  delete from public.credit_report_followup_receipts where receipt_id is not null;
  delete from public.credit_report_followup_obligations where id is not null;
  delete from public.contacts where id is not null;
  delete from public.live_webinar_sessions where id is not null;
  delete from public.settings where key is not null;

  insert into public.contacts select * from jsonb_populate_recordset(null::public.contacts, public.upgrade_live_crm_rows_v1('contacts',table_data->'contacts'));
  get diagnostics restored_contacts = row_count;
  -- Payment requests precede enrollments, whose composite FK references them.
  insert into public.payment_requests select * from jsonb_populate_recordset(null::public.payment_requests, coalesce(table_data->'payment_requests', '[]'::jsonb));
  insert into public.payment_request_events(id,request_id,actor_id,actor_name,action,details,created_at)
    select id,request_id,actor_id,actor_name,action,details,created_at
    from jsonb_populate_recordset(null::public.payment_request_events, coalesce(table_data->'payment_request_events', '[]'::jsonb));
  perform pg_catalog.setval(pg_catalog.pg_get_serial_sequence('public.payment_request_events','id'),
    greatest(coalesce((select max(id) from public.payment_request_events), 1), 1),
    exists(select 1 from public.payment_request_events));
  insert into public.events select * from jsonb_populate_recordset(null::public.events, coalesce(table_data->'events', '[]'::jsonb));
  insert into public.notes select * from jsonb_populate_recordset(null::public.notes, coalesce(table_data->'notes', '[]'::jsonb));
  insert into public.tasks select * from jsonb_populate_recordset(null::public.tasks, coalesce(table_data->'tasks', '[]'::jsonb));
  insert into public.tags select * from jsonb_populate_recordset(null::public.tags, coalesce(table_data->'tags', '[]'::jsonb));
  insert into public.contact_tags select * from jsonb_populate_recordset(null::public.contact_tags, coalesce(table_data->'contact_tags', '[]'::jsonb));
  insert into public.live_webinar_sessions select * from jsonb_populate_recordset(null::public.live_webinar_sessions, public.upgrade_live_crm_rows_v1('live_webinar_sessions',coalesce(table_data->'live_webinar_sessions','[]'::jsonb)));
  insert into public.live_webinar_registrations select * from jsonb_populate_recordset(null::public.live_webinar_registrations, public.upgrade_live_crm_rows_v1('live_webinar_registrations',coalesce(table_data->'live_webinar_registrations','[]'::jsonb)));
  insert into public.bookings select * from jsonb_populate_recordset(null::public.bookings, coalesce(table_data->'bookings', '[]'::jsonb));
  insert into public.sequence_enrollments select * from jsonb_populate_recordset(null::public.sequence_enrollments, public.upgrade_live_crm_rows_v1('sequence_enrollments',table_data->'sequence_enrollments'));
  insert into public.scheduled_messages select * from jsonb_populate_recordset(null::public.scheduled_messages, public.upgrade_live_crm_rows_v1('scheduled_messages',table_data->'scheduled_messages'));
  insert into public.settings select * from jsonb_populate_recordset(null::public.settings, coalesce(table_data->'settings', '[]'::jsonb));
  insert into public.credit_report_followup_obligations select * from jsonb_populate_recordset(null::public.credit_report_followup_obligations, coalesce(table_data->'credit_report_followup_obligations', '[]'::jsonb));
  insert into public.credit_report_followup_receipts select * from jsonb_populate_recordset(null::public.credit_report_followup_receipts, coalesce(table_data->'credit_report_followup_receipts', '[]'::jsonb));
  insert into public.credit_report_followup_contact_attempts select * from jsonb_populate_recordset(null::public.credit_report_followup_contact_attempts, coalesce(table_data->'credit_report_followup_contact_attempts', '[]'::jsonb));
  insert into public.credit_report_followup_audit(id,obligation_id,actor_id,actor_name,action,before_state,after_state,created_at)
    select id,obligation_id,actor_id,actor_name,action,before_state,after_state,created_at
    from jsonb_populate_recordset(null::public.credit_report_followup_audit, coalesce(table_data->'credit_report_followup_audit', '[]'::jsonb));
  perform pg_catalog.setval(pg_catalog.pg_get_serial_sequence('public.credit_report_followup_audit','id'),
    greatest(coalesce((select max(id) from public.credit_report_followup_audit), 1), 1),
    exists(select 1 from public.credit_report_followup_audit));

  update public.scheduled_messages set status = 'cancelled', last_error = 'Restored from full CRM backup; not resent automatically', updated_at = now() where status in ('scheduled', 'sending');
  perform public.sync_crm_notifications();
  return jsonb_build_object('contacts', restored_contacts, 'restored_at', now());
end; $$;

-- Permanent purge deletes payment rows (owner decision: Authorize.net keeps the
-- financial record). Deleted after the base records purge so that function can
-- first remove provider events for any payment-link messages.
create or replace function public.purge_crm_contact_v1(p_contact_id uuid)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_contact_id::text, 9142));
  if not exists (select 1 from public.credit_report_purge_blocks where contact_id = p_contact_id) then
    raise exception 'credit_report_purge_not_prepared';
  end if;
  if exists (select 1 from public.credit_report_upload_attempts where contact_id = p_contact_id and state = 'pending') then
    raise exception 'credit_report_upload_still_pending';
  end if;
  if exists (select 1 from storage.objects where bucket_id = 'credit-reports' and name like p_contact_id::text || '/%') then
    raise exception 'credit_report_files_not_deleted';
  end if;
  -- Recoverable trash retains queue metadata because it retains report metadata.
  -- Permanent erasure explicitly deletes it before the base contact is removed.
  delete from public.credit_report_followup_obligations where contact_id = p_contact_id;
  delete from public.credit_report_uploads where contact_id = p_contact_id;
  delete from public.credit_report_upload_sessions where contact_id = p_contact_id;
  delete from public.credit_report_upload_attempts where contact_id = p_contact_id and state = 'completed';
  delete from public.credit_report_obsolete_objects where contact_id = p_contact_id;
  perform public.purge_crm_contact_records_v1(p_contact_id);
  delete from public.payment_requests where contact_id = p_contact_id;
  return true;
end;
$$;

-- Contact privacy export v4 adds payment requests without the bearer link token
-- and with staff UUIDs removed.
alter function public.export_crm_contact_v1(uuid) rename to export_crm_contact_pre_payments_v1;
revoke all on function public.export_crm_contact_pre_payments_v1(uuid) from public, anon, authenticated, service_role;
create function public.export_crm_contact_v1(p_contact_id uuid)
returns jsonb language sql stable security definer set search_path = '' as $$
  with base as materialized (select public.export_crm_contact_pre_payments_v1(p_contact_id) as payload)
  select case when base.payload is null then null else base.payload || jsonb_build_object(
    'version', 4,
    'paymentRequests', coalesce((select jsonb_agg(
      (to_jsonb(p) - 'link_token') || jsonb_build_object('created_by', null, 'cancelled_by', null)
      order by p.created_at, p.id)
      from public.payment_requests p where p.contact_id=p_contact_id), '[]'::jsonb),
    'paymentRequestEvents', coalesce((select jsonb_agg(
      to_jsonb(ev) || jsonb_build_object('actor_id', null) order by ev.created_at, ev.id)
      from public.payment_request_events ev
      join public.payment_requests p on p.id=ev.request_id
      where p.contact_id=p_contact_id), '[]'::jsonb)
  ) end from base;
$$;

revoke all on function public.guard_payment_request_contact_v1() from public, anon, authenticated;
revoke all on function public.email_message_is_eligible(uuid,uuid,text), public.email_message_is_eligible_v2(uuid),
  public.claim_due_scheduled_emails_v2(integer,boolean), public.consume_rate_limit(text,text,integer,integer),
  public.payment_request_item_v1(uuid),
  public.create_payment_request_v1(uuid,integer,text,uuid,text,text), public.list_payment_requests_v1(uuid),
  public.find_payment_request_by_token_v1(text), public.begin_payment_checkout_v1(text),
  public.record_payment_request_event_v1(uuid,text,text,jsonb),
  public.apply_payment_transaction_v1(text,text,text,jsonb,text),
  public.cancel_payment_request_v1(uuid,uuid,uuid),
  public.begin_payment_webhook_v1(text,text,text,jsonb), public.finish_payment_webhook_v1(text,text,uuid),
  public.queue_payment_request_email_v1(uuid,uuid,uuid), public.claim_payment_request_email_v1(uuid),
  public.export_crm_backup_v4(), public.export_crm_backup_v1(), public.restore_crm_backup_v1(jsonb),
  public.purge_crm_contact_v1(uuid), public.export_crm_contact_v1(uuid)
  from public, anon, authenticated;
grant execute on function public.email_message_is_eligible_v2(uuid),
  public.claim_due_scheduled_emails_v2(integer,boolean), public.consume_rate_limit(text,text,integer,integer),
  public.create_payment_request_v1(uuid,integer,text,uuid,text,text), public.list_payment_requests_v1(uuid),
  public.find_payment_request_by_token_v1(text), public.begin_payment_checkout_v1(text),
  public.record_payment_request_event_v1(uuid,text,text,jsonb),
  public.apply_payment_transaction_v1(text,text,text,jsonb,text),
  public.cancel_payment_request_v1(uuid,uuid,uuid),
  public.begin_payment_webhook_v1(text,text,text,jsonb), public.finish_payment_webhook_v1(text,text,uuid),
  public.queue_payment_request_email_v1(uuid,uuid,uuid), public.claim_payment_request_email_v1(uuid),
  public.export_crm_backup_v4(), public.export_crm_backup_v1(), public.restore_crm_backup_v1(jsonb),
  public.purge_crm_contact_v1(uuid), public.export_crm_contact_v1(uuid)
  to service_role;
