-- Private, upload-driven 48-hour follow-up queue. This migration is additive;
-- it does not alter the public credit-check page or send customer messages.

create table public.credit_report_followup_obligations (
  id uuid primary key default gen_random_uuid(),
  -- No contacts FK: the existing recoverable-trash flow temporarily removes
  -- the active contact row while preserving private report metadata.
  contact_id uuid not null,
  due_at timestamptz not null,
  assigned_to uuid references public.crm_users(user_id) on delete set null,
  state text not null default 'open' check (state in ('open', 'completed')),
  completed_at timestamptz,
  completed_by uuid references public.crm_users(user_id) on delete set null,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  check ((state = 'open' and completed_at is null) or (state = 'completed' and completed_at is not null))
);
create unique index credit_report_followup_one_open_per_contact_idx
  on public.credit_report_followup_obligations(contact_id) where state = 'open';
create index credit_report_followup_due_idx
  on public.credit_report_followup_obligations(state, due_at, created_at);

-- Receipt IDs are retained as opaque UUIDs without a foreign key so replacing
-- a PDF does not erase the qualifying-receipt trace. No object path or bytes are
-- stored here. Contact trash retains this metadata; permanent purge deletes the
-- obligation and cascades these traces.
create table public.credit_report_followup_receipts (
  receipt_id uuid primary key,
  obligation_id uuid not null references public.credit_report_followup_obligations(id) on delete cascade,
  contact_id uuid not null,
  bureau text not null check (bureau in ('transunion', 'equifax', 'experian')),
  uploaded_at timestamptz not null,
  due_at timestamptz not null,
  recorded_at timestamptz not null default clock_timestamp()
);
create index credit_report_followup_receipts_obligation_idx
  on public.credit_report_followup_receipts(obligation_id, uploaded_at, receipt_id);

create table public.credit_report_followup_contact_attempts (
  id uuid primary key default gen_random_uuid(),
  obligation_id uuid not null references public.credit_report_followup_obligations(id) on delete cascade,
  actor_id uuid references public.crm_users(user_id) on delete set null,
  actor_name text not null,
  contacted_at timestamptz not null,
  channel text not null check (channel in ('phone', 'email', 'other')),
  outcome text not null check (outcome in ('reached', 'no_answer', 'left_message', 'other')),
  recorded_at timestamptz not null default clock_timestamp(),
  check (contacted_at <= recorded_at + interval '5 minutes')
);
create index credit_report_followup_attempts_obligation_idx
  on public.credit_report_followup_contact_attempts(obligation_id, contacted_at desc);

create table public.credit_report_followup_audit (
  id bigint generated by default as identity primary key,
  obligation_id uuid not null references public.credit_report_followup_obligations(id) on delete cascade,
  actor_id uuid references public.crm_users(user_id) on delete set null,
  actor_name text not null,
  action text not null check (action in ('assigned', 'contact_recorded')),
  before_state jsonb,
  after_state jsonb not null,
  created_at timestamptz not null default clock_timestamp()
);
create index credit_report_followup_audit_obligation_idx
  on public.credit_report_followup_audit(obligation_id, created_at desc);

alter table public.credit_report_followup_obligations enable row level security;
alter table public.credit_report_followup_receipts enable row level security;
alter table public.credit_report_followup_contact_attempts enable row level security;
alter table public.credit_report_followup_audit enable row level security;
revoke all on public.credit_report_followup_obligations, public.credit_report_followup_receipts,
  public.credit_report_followup_contact_attempts, public.credit_report_followup_audit
  from public, anon, authenticated;
grant all on public.credit_report_followup_obligations, public.credit_report_followup_receipts,
  public.credit_report_followup_contact_attempts, public.credit_report_followup_audit to service_role;
grant usage, select on sequence public.credit_report_followup_audit_id_seq to service_role;

create function public.guard_credit_report_followup_contact_v1()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if not exists (select 1 from public.contacts c where c.id = new.contact_id) then
    raise exception 'credit_report_followup_contact_unavailable';
  end if;
  return new;
end;
$$;
create trigger credit_report_followup_obligation_contact_guard
  before insert or update of contact_id on public.credit_report_followup_obligations
  for each row execute function public.guard_credit_report_followup_contact_v1();
create trigger credit_report_followup_receipt_contact_guard
  before insert or update of contact_id on public.credit_report_followup_receipts
  for each row execute function public.guard_credit_report_followup_contact_v1();

create function public.lock_credit_report_followup_contact_delete_v1()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(old.id::text, 9142));
  return old;
end;
$$;
create trigger credit_report_followup_contact_delete_lock
  before delete on public.contacts
  for each row execute function public.lock_credit_report_followup_contact_delete_v1();

create function public.credit_report_followup_receipt_time_v1()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.uploaded_at := pg_catalog.clock_timestamp();
  return new;
end;
$$;
create trigger credit_report_followup_receipt_time
  before insert or update on public.credit_report_uploads
  for each row execute function public.credit_report_followup_receipt_time_v1();

create function public.ensure_credit_report_followup_for_receipt_v1(p_receipt_id uuid)
returns uuid language plpgsql security definer set search_path = '' as $$
declare
  receipt_row public.credit_report_uploads%rowtype;
  obligation_id uuid;
  default_assignee uuid;
  event_due_at timestamptz;
begin
  select * into receipt_row from public.credit_report_uploads where id = p_receipt_id;
  if not found then return null; end if;
  if not exists (select 1 from public.contacts where id = receipt_row.contact_id) then return null; end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(receipt_row.contact_id::text, 9142));
  if (select count(distinct u.bureau) from public.credit_report_uploads u where u.contact_id = receipt_row.contact_id) < 3 then
    return null;
  end if;

  select r.obligation_id into obligation_id
  from public.credit_report_followup_receipts r where r.receipt_id = p_receipt_id;
  if obligation_id is not null then return obligation_id; end if;

  event_due_at := receipt_row.uploaded_at + interval '48 hours';
  select o.id into obligation_id
  from public.credit_report_followup_obligations o
  where o.contact_id = receipt_row.contact_id and o.state = 'open'
  for update;

  if obligation_id is null then
    select c.owner_id into default_assignee
    from public.contacts c join public.crm_users u on u.user_id = c.owner_id
    where c.id = receipt_row.contact_id and u.role <> 'readonly';
    if default_assignee is null then
      select u.user_id into default_assignee from public.crm_users u
      where u.role = 'admin' order by u.created_at, u.user_id limit 1;
    end if;
    insert into public.credit_report_followup_obligations(contact_id, due_at, assigned_to)
    values (receipt_row.contact_id, event_due_at, default_assignee)
    returning id into obligation_id;
    insert into public.credit_report_followup_audit(obligation_id, actor_name, action, after_state)
    values (obligation_id, 'system', 'assigned', jsonb_build_object('assignedTo', default_assignee, 'source', 'automatic'));
  else
    update public.credit_report_followup_obligations
      set due_at = least(due_at, event_due_at), updated_at = pg_catalog.clock_timestamp()
      where id = obligation_id;
  end if;

  insert into public.credit_report_followup_receipts(receipt_id, obligation_id, contact_id, bureau, uploaded_at, due_at)
  values (p_receipt_id, obligation_id, receipt_row.contact_id, receipt_row.bureau, receipt_row.uploaded_at, event_due_at)
  on conflict (receipt_id) do nothing;
  return obligation_id;
end;
$$;

create function public.capture_credit_report_followup_receipt_v1()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  perform public.ensure_credit_report_followup_for_receipt_v1(new.id);
  return new;
end;
$$;
create trigger credit_report_followup_receipt_capture
  after insert or update on public.credit_report_uploads
  for each row execute function public.capture_credit_report_followup_receipt_v1();

create function public.reconcile_credit_report_followup_receipts_v1(p_limit integer default 100)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare candidate record; scanned integer := 0; created integer := 0; has_more boolean := false;
begin
  if p_limit < 1 or p_limit > 500 then raise exception 'credit_report_followup_limit_invalid'; end if;
  for candidate in
    with full_contacts as (
      select u.contact_id from public.credit_report_uploads u
      group by u.contact_id having count(distinct u.bureau) = 3
    ), latest as (
      select distinct on (u.contact_id) u.id, u.contact_id
      from public.credit_report_uploads u join full_contacts f on f.contact_id = u.contact_id
      order by u.contact_id, u.uploaded_at desc, u.id desc
    )
    select l.id as receipt_id from latest l
    where not exists (select 1 from public.credit_report_followup_receipts r where r.receipt_id = l.id)
    order by l.id limit p_limit + 1
  loop
    if scanned >= p_limit then has_more := true; exit; end if;
    scanned := scanned + 1;
    if public.ensure_credit_report_followup_for_receipt_v1(candidate.receipt_id) is not null then created := created + 1; end if;
  end loop;
  return jsonb_build_object('scanned', scanned, 'reconciled', created, 'hasMore', has_more);
end;
$$;

create or replace function public.finish_credit_report_attempt_reconciliation_v1(
  p_attempt_id uuid, p_claim_token uuid, p_object_exists boolean, p_object_removed boolean default false
)
returns text language plpgsql security definer set search_path = '' as $$
declare attempt_row public.credit_report_upload_attempts%rowtype; has_receipt boolean;
begin
  select * into attempt_row from public.credit_report_upload_attempts where id = p_attempt_id;
  if not found then raise exception 'credit_report_attempt_missing'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(attempt_row.contact_id::text, 9142));
  select * into attempt_row from public.credit_report_upload_attempts where id = p_attempt_id for update;
  if attempt_row.reconciliation_token is distinct from p_claim_token then raise exception 'credit_report_claim_lost'; end if;
  select exists (select 1 from public.credit_report_uploads u where u.id = attempt_row.id and u.contact_id = attempt_row.contact_id and u.object_path = attempt_row.object_path)
    into has_receipt;
  if p_object_exists and has_receipt then
    if not exists (select 1 from storage.objects where bucket_id = 'credit-reports' and name = attempt_row.object_path) then
      raise exception 'credit_report_object_not_confirmed';
    end if;
    perform public.ensure_credit_report_followup_for_receipt_v1(attempt_row.id);
    update public.credit_report_upload_attempts set state = 'completed', completed_at = coalesce(completed_at, now()),
      upload_lease_until = null, reconciliation_token = null, reconciliation_lease_until = null,
      next_reconcile_at = now() + interval '24 hours', last_failure_code = null where id = p_attempt_id;
    return 'completed';
  end if;
  if p_object_exists and not p_object_removed then raise exception 'credit_report_object_removal_unconfirmed'; end if;
  if exists (select 1 from storage.objects where bucket_id = 'credit-reports' and name = attempt_row.object_path) then
    raise exception 'credit_report_object_still_exists';
  end if;
  delete from public.credit_report_uploads u where u.id = attempt_row.id and u.contact_id = attempt_row.contact_id and u.object_path = attempt_row.object_path;
  update public.credit_report_upload_attempts set state = 'abandoned', completed_at = null,
    upload_lease_until = null, reconciliation_token = null, reconciliation_lease_until = null,
    next_reconcile_at = now() + interval '1 hour', last_failure_code = null where id = p_attempt_id;
  return 'abandoned';
end;
$$;

create function public.list_credit_report_followups_v1()
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('items', coalesce(jsonb_agg(item order by state_sort, due_at, created_at), '[]'::jsonb))
  from (
    select jsonb_build_object(
      'id', o.id, 'contactId', o.contact_id, 'contactName', c.name, 'contactEmail', c.email,
      'state', o.state, 'dueAt', o.due_at, 'assignedTo', o.assigned_to,
      'assignedName', assigned.display_name, 'createdAt', o.created_at, 'completedAt', o.completed_at,
      'receipts', coalesce((select jsonb_agg(jsonb_build_object(
        'bureau', r.bureau, 'uploadedAt', r.uploaded_at, 'dueAt', r.due_at
      ) order by r.uploaded_at, r.receipt_id) from public.credit_report_followup_receipts r where r.obligation_id = o.id), '[]'::jsonb),
      'attempts', coalesce((select jsonb_agg(jsonb_build_object(
        'actorName', a.actor_name, 'contactedAt', a.contacted_at, 'channel', a.channel,
        'outcome', a.outcome, 'recordedAt', a.recorded_at
      ) order by a.contacted_at desc, a.id desc) from public.credit_report_followup_contact_attempts a where a.obligation_id = o.id), '[]'::jsonb)
    ) as item, o.state,
    case when o.state = 'open' then 0 else 1 end as state_sort, o.due_at, o.created_at
    from public.credit_report_followup_obligations o
    join public.contacts c on c.id = o.contact_id
    left join public.crm_users assigned on assigned.user_id = o.assigned_to
    order by state_sort, o.due_at, o.created_at
    limit 500
  ) q;
$$;

create function public.list_credit_report_followup_assignees_v1()
returns jsonb language sql stable security definer set search_path = '' as $$
  select coalesce(jsonb_agg(jsonb_build_object('id', user_id, 'name', coalesce(display_name, 'CRM user'), 'role', role) order by display_name, user_id), '[]'::jsonb)
  from public.crm_users where role in ('admin', 'staff');
$$;

create function public.assign_credit_report_followup_v1(p_obligation_id uuid, p_assignee_id uuid, p_actor_id uuid)
returns boolean language plpgsql security definer set search_path = '' as $$
declare before_assignee uuid; actor_name text; assignee_role public.crm_role;
begin
  select display_name into actor_name from public.crm_users where user_id = p_actor_id and role in ('admin', 'staff');
  if not found then raise exception 'credit_report_followup_actor_invalid'; end if;
  if p_assignee_id is not null then
    select role into assignee_role from public.crm_users where user_id = p_assignee_id;
    if not found or assignee_role not in ('admin', 'staff') then raise exception 'credit_report_followup_assignee_invalid'; end if;
  end if;
  select assigned_to into before_assignee from public.credit_report_followup_obligations
    where id = p_obligation_id and state = 'open' for update;
  if not found then raise exception 'credit_report_followup_missing'; end if;
  if before_assignee is not distinct from p_assignee_id then return true; end if;
  update public.credit_report_followup_obligations set assigned_to = p_assignee_id, updated_at = pg_catalog.clock_timestamp()
    where id = p_obligation_id;
  insert into public.credit_report_followup_audit(obligation_id, actor_id, actor_name, action, before_state, after_state)
  values (p_obligation_id, p_actor_id, coalesce(actor_name, 'CRM user'), 'assigned',
    jsonb_build_object('assignedTo', before_assignee), jsonb_build_object('assignedTo', p_assignee_id));
  return true;
end;
$$;

create function public.record_credit_report_followup_contact_v1(
  p_obligation_id uuid, p_actor_id uuid, p_contacted_at timestamptz, p_channel text, p_outcome text
)
returns uuid language plpgsql security definer set search_path = '' as $$
declare actor_name text; attempt_id uuid := gen_random_uuid(); previous_state text; obligation_created_at timestamptz;
begin
  if p_channel not in ('phone', 'email', 'other') or p_outcome not in ('reached', 'no_answer', 'left_message', 'other') then
    raise exception 'credit_report_followup_outcome_invalid';
  end if;
  if p_contacted_at is null or p_contacted_at > pg_catalog.clock_timestamp() + interval '5 minutes' then
    raise exception 'credit_report_followup_time_invalid';
  end if;
  select display_name into actor_name from public.crm_users where user_id = p_actor_id and role in ('admin', 'staff');
  if not found then raise exception 'credit_report_followup_actor_invalid'; end if;
  select state, created_at into previous_state, obligation_created_at from public.credit_report_followup_obligations
    where id = p_obligation_id and state = 'open' for update;
  if not found then raise exception 'credit_report_followup_missing'; end if;
  if p_contacted_at < obligation_created_at then raise exception 'credit_report_followup_time_invalid'; end if;
  insert into public.credit_report_followup_contact_attempts(id, obligation_id, actor_id, actor_name, contacted_at, channel, outcome)
  values (attempt_id, p_obligation_id, p_actor_id, coalesce(actor_name, 'CRM user'), p_contacted_at, p_channel, p_outcome);
  if p_outcome = 'reached' then
    update public.credit_report_followup_obligations set state = 'completed', completed_at = p_contacted_at,
      completed_by = p_actor_id, updated_at = pg_catalog.clock_timestamp() where id = p_obligation_id;
  else
    update public.credit_report_followup_obligations set updated_at = pg_catalog.clock_timestamp() where id = p_obligation_id;
  end if;
  insert into public.credit_report_followup_audit(obligation_id, actor_id, actor_name, action, before_state, after_state)
  values (p_obligation_id, p_actor_id, coalesce(actor_name, 'CRM user'), 'contact_recorded',
    jsonb_build_object('state', previous_state), jsonb_build_object(
      'attemptId', attempt_id, 'contactedAt', p_contacted_at, 'channel', p_channel,
      'outcome', p_outcome, 'state', case when p_outcome = 'reached' then 'completed' else 'open' end
    ));
  return attempt_id;
end;
$$;

create function public.export_crm_backup_v3()
returns jsonb language sql stable security definer set search_path = '' as $$
  with base as materialized (select public.export_crm_backup_v2() as payload)
  select jsonb_set(jsonb_set(base.payload, '{version}', '3'::jsonb), '{tables}',
    (base.payload->'tables') || jsonb_build_object(
      'credit_report_followup_obligations', coalesce((select jsonb_agg(to_jsonb(o) || jsonb_build_object('assigned_to', null, 'completed_by', null)) from public.credit_report_followup_obligations o where exists(select 1 from public.contacts c where c.id=o.contact_id)), '[]'::jsonb),
      'credit_report_followup_receipts', coalesce((select jsonb_agg(to_jsonb(r)) from public.credit_report_followup_receipts r where exists(select 1 from public.contacts c where c.id=r.contact_id)), '[]'::jsonb),
      'credit_report_followup_contact_attempts', coalesce((select jsonb_agg(to_jsonb(a) || jsonb_build_object('actor_id', null)) from public.credit_report_followup_contact_attempts a join public.credit_report_followup_obligations o on o.id=a.obligation_id where exists(select 1 from public.contacts c where c.id=o.contact_id)), '[]'::jsonb),
      'credit_report_followup_audit', coalesce((select jsonb_agg(to_jsonb(a) || jsonb_build_object(
        'actor_id', null,
        'before_state', case when a.before_state is null then null else a.before_state - 'assignedTo' end,
        'after_state', case when a.after_state is null then null else a.after_state - 'assignedTo' end
      )) from public.credit_report_followup_audit a join public.credit_report_followup_obligations o on o.id=a.obligation_id where exists(select 1 from public.contacts c where c.id=o.contact_id)), '[]'::jsonb)
    )) from base;
$$;

create or replace function public.purge_crm_contact_v1(p_contact_id uuid)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_contact_id::text, 9142));
  if not exists (select 1 from public.credit_report_purge_blocks where contact_id = p_contact_id) then
    raise exception 'credit_report_purge_not_prepared';
  end if;
  if exists (select 1 from public.credit_report_upload_attempts where contact_id = p_contact_id and state = 'pending') then
    raise exception 'credit_report_upload_still_pending';
  end if;
  if exists (select 1 from storage.objects where bucket_id = 'credit-reports' and name like p_contact_id::text || '/%') then
    raise exception 'credit_report_files_not_deleted';
  end if;
  -- Recoverable trash retains queue metadata because it retains report metadata.
  -- Permanent erasure explicitly deletes it before the base contact is removed.
  delete from public.credit_report_followup_obligations where contact_id = p_contact_id;
  delete from public.credit_report_uploads where contact_id = p_contact_id;
  delete from public.credit_report_upload_sessions where contact_id = p_contact_id;
  delete from public.credit_report_upload_attempts where contact_id = p_contact_id and state = 'completed';
  delete from public.credit_report_obsolete_objects where contact_id = p_contact_id;
  perform public.purge_crm_contact_records_v1(p_contact_id);
  return true;
end;
$$;

create or replace function public.restore_crm_backup_v1(p_backup jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare table_data jsonb := p_backup->'tables'; restored_contacts integer;
begin
  if coalesce(p_backup->>'format', '') <> 'vance-crm-backup' or coalesce((p_backup->>'version')::integer, 0) not in (1,2,3) then raise exception 'unsupported_backup_format'; end if;
  if jsonb_typeof(table_data) <> 'object' then raise exception 'missing_backup_tables'; end if;
  delete from public.scheduled_messages where id is not null;
  delete from public.sequence_enrollments where id is not null;
  delete from public.bookings where id is not null;
  delete from public.notes where id is not null;
  delete from public.tasks where id is not null;
  delete from public.contact_tags where contact_id is not null;
  delete from public.tags where id is not null;
  delete from public.events where id is not null;
  delete from public.live_webinar_registrations where id is not null;
  delete from public.credit_report_followup_audit where id is not null;
  delete from public.credit_report_followup_contact_attempts where id is not null;
  delete from public.credit_report_followup_receipts where receipt_id is not null;
  delete from public.credit_report_followup_obligations where id is not null;
  delete from public.contacts where id is not null;
  delete from public.live_webinar_sessions where id is not null;
  delete from public.settings where key is not null;

  insert into public.contacts select * from jsonb_populate_recordset(null::public.contacts, public.upgrade_live_crm_rows_v1('contacts',table_data->'contacts'));
  get diagnostics restored_contacts = row_count;
  insert into public.events select * from jsonb_populate_recordset(null::public.events, coalesce(table_data->'events', '[]'::jsonb));
  insert into public.notes select * from jsonb_populate_recordset(null::public.notes, coalesce(table_data->'notes', '[]'::jsonb));
  insert into public.tasks select * from jsonb_populate_recordset(null::public.tasks, coalesce(table_data->'tasks', '[]'::jsonb));
  insert into public.tags select * from jsonb_populate_recordset(null::public.tags, coalesce(table_data->'tags', '[]'::jsonb));
  insert into public.contact_tags select * from jsonb_populate_recordset(null::public.contact_tags, coalesce(table_data->'contact_tags', '[]'::jsonb));
  insert into public.live_webinar_sessions select * from jsonb_populate_recordset(null::public.live_webinar_sessions, public.upgrade_live_crm_rows_v1('live_webinar_sessions',coalesce(table_data->'live_webinar_sessions','[]'::jsonb)));
  insert into public.live_webinar_registrations select * from jsonb_populate_recordset(null::public.live_webinar_registrations, public.upgrade_live_crm_rows_v1('live_webinar_registrations',coalesce(table_data->'live_webinar_registrations','[]'::jsonb)));
  insert into public.bookings select * from jsonb_populate_recordset(null::public.bookings, coalesce(table_data->'bookings', '[]'::jsonb));
  insert into public.sequence_enrollments select * from jsonb_populate_recordset(null::public.sequence_enrollments, public.upgrade_live_crm_rows_v1('sequence_enrollments',table_data->'sequence_enrollments'));
  insert into public.scheduled_messages select * from jsonb_populate_recordset(null::public.scheduled_messages, public.upgrade_live_crm_rows_v1('scheduled_messages',table_data->'scheduled_messages'));
  insert into public.settings select * from jsonb_populate_recordset(null::public.settings, coalesce(table_data->'settings', '[]'::jsonb));
  insert into public.credit_report_followup_obligations select * from jsonb_populate_recordset(null::public.credit_report_followup_obligations, coalesce(table_data->'credit_report_followup_obligations', '[]'::jsonb));
  insert into public.credit_report_followup_receipts select * from jsonb_populate_recordset(null::public.credit_report_followup_receipts, coalesce(table_data->'credit_report_followup_receipts', '[]'::jsonb));
  insert into public.credit_report_followup_contact_attempts select * from jsonb_populate_recordset(null::public.credit_report_followup_contact_attempts, coalesce(table_data->'credit_report_followup_contact_attempts', '[]'::jsonb));
  insert into public.credit_report_followup_audit(id,obligation_id,actor_id,actor_name,action,before_state,after_state,created_at)
    select id,obligation_id,actor_id,actor_name,action,before_state,after_state,created_at
    from jsonb_populate_recordset(null::public.credit_report_followup_audit, coalesce(table_data->'credit_report_followup_audit', '[]'::jsonb));
  perform pg_catalog.setval(pg_catalog.pg_get_serial_sequence('public.credit_report_followup_audit','id'),
    greatest(coalesce((select max(id) from public.credit_report_followup_audit), 1), 1),
    exists(select 1 from public.credit_report_followup_audit));

  update public.scheduled_messages set status = 'cancelled', last_error = 'Restored from full CRM backup; not resent automatically', updated_at = now() where status in ('scheduled', 'sending');
  perform public.sync_crm_notifications();
  return jsonb_build_object('contacts', restored_contacts, 'restored_at', now());
end; $$;

revoke all on function public.credit_report_followup_receipt_time_v1() from public, anon, authenticated;
revoke all on function public.guard_credit_report_followup_contact_v1() from public, anon, authenticated;
revoke all on function public.lock_credit_report_followup_contact_delete_v1() from public, anon, authenticated;
revoke all on function public.ensure_credit_report_followup_for_receipt_v1(uuid) from public, anon, authenticated;
revoke all on function public.capture_credit_report_followup_receipt_v1() from public, anon, authenticated;
revoke all on function public.reconcile_credit_report_followup_receipts_v1(integer) from public, anon, authenticated;
revoke all on function public.list_credit_report_followups_v1() from public, anon, authenticated;
revoke all on function public.list_credit_report_followup_assignees_v1() from public, anon, authenticated;
revoke all on function public.assign_credit_report_followup_v1(uuid,uuid,uuid) from public, anon, authenticated;
revoke all on function public.record_credit_report_followup_contact_v1(uuid,uuid,timestamptz,text,text) from public, anon, authenticated;
revoke all on function public.export_crm_backup_v3() from public, anon, authenticated;
revoke all on function public.restore_crm_backup_v1(jsonb) from public, anon, authenticated;
grant execute on function public.reconcile_credit_report_followup_receipts_v1(integer),
  public.list_credit_report_followups_v1(), public.list_credit_report_followup_assignees_v1(),
  public.assign_credit_report_followup_v1(uuid,uuid,uuid),
  public.record_credit_report_followup_contact_v1(uuid,uuid,timestamptz,text,text),
  public.export_crm_backup_v3(), public.restore_crm_backup_v1(jsonb) to service_role;

-- Existing full sets predate atomic capture. One current latest receipt is the
-- only qualifying event recoverable because the old schema replaced each
-- bureau row in place and did not preserve its earlier receipt history.
do $$
declare latest_receipt uuid;
begin
  for latest_receipt in
    with full_contacts as (
      select contact_id from public.credit_report_uploads group by contact_id having count(distinct bureau) = 3
    )
    select distinct on (u.contact_id) u.id from public.credit_report_uploads u
      join full_contacts f on f.contact_id = u.contact_id
      order by u.contact_id, u.uploaded_at desc, u.id desc
  loop
    perform public.ensure_credit_report_followup_for_receipt_v1(latest_receipt);
  end loop;
end;
$$;

create or replace function public.export_crm_backup_v1()
returns jsonb language sql stable security definer set search_path = '' as $$
  select public.export_crm_backup_v3();
$$;
revoke all on function public.export_crm_backup_v1() from public, anon, authenticated;
grant execute on function public.export_crm_backup_v1() to service_role;

-- A contact privacy export includes the new contact-linked queue records, as
-- the existing live-webinar wrapper includes registrations. Keep report object
-- metadata out and redact staff UUIDs in the same way as the v3 CRM backup.
alter function public.export_crm_contact_v1(uuid) rename to export_crm_contact_pre_followup_v1;
revoke all on function public.export_crm_contact_pre_followup_v1(uuid) from public, anon, authenticated, service_role;
create function public.export_crm_contact_v1(p_contact_id uuid)
returns jsonb language sql stable security definer set search_path = '' as $$
  with base as materialized (select public.export_crm_contact_pre_followup_v1(p_contact_id) as payload)
  select case when base.payload is null then null else base.payload || jsonb_build_object(
    'version', 3,
    'creditReportFollowupObligations', coalesce((select jsonb_agg(
      to_jsonb(o) || jsonb_build_object('assigned_to', null, 'completed_by', null)
      order by o.created_at, o.id)
      from public.credit_report_followup_obligations o where o.contact_id=p_contact_id), '[]'::jsonb),
    'creditReportFollowupReceipts', coalesce((select jsonb_agg(to_jsonb(r) order by r.uploaded_at, r.receipt_id)
      from public.credit_report_followup_receipts r where r.contact_id=p_contact_id), '[]'::jsonb),
    'creditReportFollowupContactAttempts', coalesce((select jsonb_agg(
      to_jsonb(a) || jsonb_build_object('actor_id', null) order by a.contacted_at, a.id)
      from public.credit_report_followup_contact_attempts a
      join public.credit_report_followup_obligations o on o.id=a.obligation_id
      where o.contact_id=p_contact_id), '[]'::jsonb),
    'creditReportFollowupAudit', coalesce((select jsonb_agg(
      to_jsonb(a) || jsonb_build_object(
        'actor_id', null,
        'before_state', case when a.before_state is null then null else a.before_state - 'assignedTo' end,
        'after_state', case when a.after_state is null then null else a.after_state - 'assignedTo' end
      ) order by a.created_at, a.id)
      from public.credit_report_followup_audit a
      join public.credit_report_followup_obligations o on o.id=a.obligation_id
      where o.contact_id=p_contact_id), '[]'::jsonb)
  ) end from base;
$$;
revoke all on function public.export_crm_contact_v1(uuid) from public, anon, authenticated;
grant execute on function public.export_crm_contact_v1(uuid) to service_role;
